{% set version = "1.0.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sccore
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sccore_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sccore/sccore_{{ version }}.tar.gz
  sha256: 8fe2d2e4de01efaffe3e79aa8b8fc7bbef6b6c6e3fa8f9c1fde56c509f95548a

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-matrix                     # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-rcpparmadillo              # [build_platform != target_platform]
    - r-rcppeigen                  # [build_platform != target_platform]
    - r-rcppprogress               # [build_platform != target_platform]
    - r-dplyr                      # [build_platform != target_platform]
    - r-ggplot2                    # [build_platform != target_platform]
    - r-ggrepel                    # [build_platform != target_platform]
    - r-igraph                     # [build_platform != target_platform]
    - r-irlba                      # [build_platform != target_platform]
    - r-magrittr                   # [build_platform != target_platform]
    - r-proc                       # [build_platform != target_platform]
    - r-pbmcapply                  # [build_platform != target_platform]
    - r-rlang                      # [build_platform != target_platform]
    - r-scales                     # [build_platform != target_platform]
    - r-tibble                     # [build_platform != target_platform]
    - r-uwot                       # [build_platform != target_platform]
    - r-withr                      # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppeigen
    - r-rcppprogress
    - r-dplyr
    - r-ggplot2
    - r-ggrepel
    - r-igraph
    - r-irlba
    - r-magrittr
    - r-proc
    - r-pbmcapply
    - r-rlang
    - r-scales
    - r-tibble
    - r-uwot
    - r-withr
  run:
    - r-base
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppeigen
    - r-rcppprogress
    - r-dplyr
    - r-ggplot2
    - r-ggrepel
    - r-igraph
    - r-irlba
    - r-magrittr
    - r-proc
    - r-pbmcapply
    - r-rlang
    - r-scales
    - r-tibble
    - r-uwot
    - r-withr

test:
  commands:
    - $R -e "library('sccore')"           # [not win]
    - "\"%R%\" -e \"library('sccore')\""  # [win]

about:
  home: https://github.com/kharchenkolab/sccore
  license: GPL-3.0-only
  summary: Core utilities for single-cell RNA-seq data analysis. Contained within are utility functions for working with differential expression (DE) matrices and count matrices, a collection of functions for manipulating and plotting data via 'ggplot2', and functions to work with cell graphs and cell embeddings. Graph-based
    methods include embedding kNN cell graphs into a UMAP <doi:10.21105/joss.00861>, collapsing vertices of each cluster in the graph, and propagating graph labels.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - raivivek
